AWSTemplateFormatVersion: '2010-09-09'
Description: Personal MWAA Starter Template - Minimal Setup

Parameters:
  EnvironmentName:
    Type: String
    Default: mwaa-starter
  AirflowVersion:
    Type: String
    Default: '2.7.2'

Resources:
  MWAAExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: airflow-env.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess

  DAGBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${EnvironmentName}-dags"

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true

  Subnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, !GetAZs '']

  Subnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: !Select [1, !GetAZs '']

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: MWAA access group
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  MWAAEnvironment:
    Type: AWS::MWAA::Environment
    Properties:
      Name: !Ref EnvironmentName
      AirflowVersion: !Ref AirflowVersion
      DagS3Path: dags/
      EnvironmentClass: mw1.small
      ExecutionRoleArn: !GetAtt MWAAExecutionRole.Arn
      SourceBucketArn: !GetAtt DAGBucket.Arn
      NetworkConfiguration:
        SecurityGroupIds:
          - !Ref SecurityGroup
        SubnetIds:
          - !Ref Subnet1
          - !Ref Subnet2
      WebserverAccessMode: PUBLIC_ONLY
      LoggingConfiguration:
        DagProcessingLogs:
          Enabled: true
          LogLevel: INFO
        SchedulerLogs:
          Enabled: true
          LogLevel: INFO
        TaskLogs:
          Enabled: true
          LogLevel: INFO
        WebserverLogs:
          Enabled: true
          LogLevel: INFO
        WorkerLogs:
          Enabled: true
          LogLevel: INFO

Outputs:
  WebUI:
    Description: MWAA Web UI Link
    Value: !Sub "https://${EnvironmentName}.airflow.${AWS::Region}.amazonaws.com"
  BucketName:
    Description: Upload DAGs to this bucket
    Value: !Ref DAGBucket
