AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation template for a DynamoDB table with a Global Secondary Index and Streams"

Resources:
  MyDynamoDBTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: "MyDynamoDBTable"
      AttributeDefinitions:
        - AttributeName: "UserID"
          AttributeType: "S"
        - AttributeName: "OrderID"
          AttributeType: "S"
        - AttributeName: "CreatedAt"
          AttributeType: "N"
      KeySchema:
        - AttributeName: "UserID"
          KeyType: "HASH"
        - AttributeName: "OrderID"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"  # Change to "PROVISIONED" if needed
      GlobalSecondaryIndexes:
        - IndexName: "CreatedAtIndex"
          KeySchema:
            - AttributeName: "CreatedAt"
              KeyType: "HASH"
            - AttributeName: "OrderID"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
      StreamSpecification:
        StreamViewType: "NEW_AND_OLD_IMAGES"
      SSESpecification:
        SSEEnabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: "Environment"
          Value: "Production"
        - Key: "Project"
          Value: "MyProject"

Outputs:
  DynamoDBTableName:
    Description: "The name of the DynamoDB table"
    Value: !Ref MyDynamoDBTable
  DynamoDBTableArn:
    Description: "The ARN of the DynamoDB table"
    Value: !GetAtt MyDynamoDBTable.Arn
